pref("extensions.zotero.auto-index.delay", 60)
pref("extensions.zotero.auto-index.index-pdfs", true)
pref("extensions.zotero.auto-index.extract-annotations", true)
pref("extensions.zotero.auto-index.index.batch", 50)
pref("extensions.zotero.auto-index.zotfile.batch", 10)
pref("extensions.zotero.auto-index.debug", true)
pref("extensions.zotero.auto-index.reindexOnPrefChange", false)
